### ISSUE TITLE
Update guide on v11 release

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/lamp-guide#78]
When version 11 is released, update guide:

* Create '10' directory, copy current material into it, link to it from main guide.
* Move relevant "future" material into body.

**Comment by david-a-wheeler** [comment]
See also texr here on reducing screen space use: https://github.com/expln/metamath-lamp/issues/67#issuecomment-1586723337

**Comment by david-a-wheeler** [comment]
Related (be sure to review):

*https://github.com/expln/metamath-lamp/issues/16 including 
https://github.com/expln/metamath-lamp/issues/16#issuecomment-1588046164

**Comment by david-a-wheeler** [comment]
Version 11 appears imminent.

I've developing a pull request here that will update the guide for version 11: https://github.com/metamath/lamp-guide/pull/85

**Comment by david-a-wheeler** [comment]
I should have created a new 11/ directory, so I can see generated results. I will probably move files so the version 11 materials are in 11/ and restore the version 10 files to their location. That may make following changes harder, sorry about that. But I need to make sure the generated results are OK before I post them for real :-).

**Comment by david-a-wheeler** [comment]
GIt shows the history of the changes, but it's probably too complex to be useful.

The updated document is in `11/index.md` while the current one is in `index.md`. The best way to see the changes is:

~~~~
diff -u index.md 11/index.md
~~~~

I made a massive number of changes all over the place (long-click, etc.). I moved the explorer material into the main body, and reorganized the tutorial. It's now 2p2e4, explorer, syl, and then reccot. I wanted the explorer early, right after 2p2e4, so I can start down that path in the first video. Then syl naturally follows. The reccot proof is longer, and thus makes more sense later.

The long-click is a huge improvement in the UI, but it did cause a lot of changes in the text. I'm not complaining, though. The tool is now 100% usable on laptops *and* smartphones, and it's relatively easy to explain how to use.

**Comment by david-a-wheeler** [comment]
Currently the version 10 document is the visible page. You can view the latest draft for version 11 here:

https://lamp-guide.metamath.org/11/

**Comment by david-a-wheeler** [comment]
@expln - the guide in 11/index.md is basically ready fir release. You can see it here: https://lamp-guide.metamath.org/11/

The changes are tracked by git, but I messed up how I handled it, so reading the individual git commits will be overwhelming. Especially silence I rearranged the tutorial to give the explorer more prominence.

Comments welcome, and I think I've figured out a better process for next time.

**Comment by expln** [comment]
@david-a-wheeler

Thanks for preparing the guide for the version 11! I will review it soon.

At the moment I would like to discuss how we will keep versions of the app and the guide in sync.

I want to just increase version by one each time I do a release independently of how big change compared to the previous release. For example, suppose I released v11. But then a bug is found and I made a fix. In that case I will release another version - v12 - even though the difference between v11 and v12 is only one small bugfix. This also implies that there potentially could be very large version numbers like v73 or even v791. I know this is very unusual for software. I did some research on why software versions usually have the form of few numbers concatenated via dots like `3.12.608`, or more generally `maj.min.build` or `maj.min.patch`. I found only one reason - to include some meaning to the version number. It is good for libraries because developers may easily understand when upgrade to a newer version is less risky and when more risky. For programs which exist in few versions, like paid ones, this may help users to decide what version they may download. But mm-lamp is not a library, and I am not planing to support many versions. Only one version - the latest one - will be supported and evolved further. Moreover, mm-lamp may not need version at all like any other site in the Internet. I introduced versions to solve two issues. One issue is to prevent caching of application files by browsers. So each time a new change is uploaded to the server, browsers will read it by a new URL and caching will not result in mysterious errors when the app works well for one user but doesn't work for another. Another issue - to be able to quickly switch to one of the previous versions if the latest version has a critical bug. So, I think just incrementing version number will be fine for the app.

I think it also will be fine for the documentation, but I am not sure, actually.

**Comment by david-a-wheeler** [comment]
Please *do* *NOT* disable caching. Smartphones (including mine) are *routinely* out of network access for long periods of time. A big draw of "explorer" in metamath-lamp is that it works when the internet isn't available.

Also, please just use Major.minor.patch like almost everyone else. It has nothing to do with being paid, almost all non-paid OSS projects use major.minor.patch. If it's a small change, it was version 11.0.0 and now it's 11.0.1. No problem. It's okay if you only post the current version on the website. If you force users to switch without their decision, their work may suddenly be lost because of an internal format change that you might not even realize was an issue.

I don't think it's a problem if the documentation goes a little out of sync. But I'll try to document major version number changes.

**Comment by david-a-wheeler** [comment]
When the *site* stores all the data there's no need for a version number, because you can routinely update the data stored at the server. But users will store data *locally* in this app, which is a good thing, but it makes it harder to quietly upgrade its data - especially if there's an incompatible change.

**Comment by expln** [comment]
The problem with versions of the form `11.0.1` is that it is the same as what I want to do but the version will always be prefixed with `11.0.`. Sometimes I will change the prefix `11.0.` -> `12.0.`. But I am going to deliver small changes in continues manner. So I don't expect major changes at once. So, for me, it looks like just always prepending a version number with unnecessary prefix. I don't understand why I should make versions of mm-lamp meaningful. I will always document all the changes in the issues, so if you want to update the guide only for some big changes you may monitor all the changes and decide when it is the time to update the guide. I also can inform you when I think the guide may be updated (by creating a PR in the guide repo with my proposed changes, for example, or just by writing you a message).

> If you force users to switch without their decision, their work may suddenly be lost because of an internal format change that you might not even realize was an issue.

This is how mm-lamp works now. If a user uses the "latest" URL `https://expln.github.io/lamp/latest/index.html` then they will be redirected to the latest version without their confirmation. If the user doesn't want this to happen, they may use a "versioned" URL like this, for example, `https://expln.github.io/lamp/v11/index.html` - this will always load that particular version.

Switching from an older version to a newer version should not result in data loss. I am trying to support all the previously introduced formats, converting old ones to new ones if needed. Switching in the opposite direction may, of course, result in some issues with format mismatch. But previous versions are "frozen" and they cannot foresee the future formats, so that should be expected.


> Please do NOT disable caching. Smartphones (including mine) are routinely out of network access for long periods of time. A big draw of "explorer" in metamath-lamp is that it works when the internet isn't available.

Caching for the "latest" URL has been disabled since version 6 (or even earlier). Caching for the "versioned" URLs is not disabled. So if you stored a "versioned" URL in your browser's bookmarks then the problem you mentioned should not happen. However, I am not sure. Because even if caching is not disabled, a browser still may try to download data from the Internet. Probably it makes sense to explicitly enable caching for "versioned" URLs. Have you noticed any problems like that so far?

**Comment by david-a-wheeler** [comment]
I guess if someone cares about a specific release they can always consult git :-). I certainly agree with release early, release often :-).

My bigger concern is running on smartphones that occasionally get disconnected from the network. I'm going to focus on a few other things first & then hopefully get a chance to do some testing.

**Comment by expln** [comment]
> My bigger concern is running on smartphones that occasionally get disconnected from the network. I'm going to focus on a few other things first & then hopefully get a chance to do some testing.

Thank you. One more thing which may be helpful during testing - the app never tries to reload itself from the Internet once it is loaded and started working. It reloads only when a user intentionally reloads the page with the app.

**Comment by david-a-wheeler** [comment]
> the app never tries to reload itself from the Internet once it is loaded and started working. It reloads only when a user intentionally reloads the page with the app.

Oh! That's a relief. I guess I don't understand your comment about disabling caching then. Can you please help me understand?

**Comment by david-a-wheeler** [comment]
Regarding version ids, you're describing a situation I haven't deeply considered before. I guess it's back to first principles, starting with analogies to systems I know.

* I release many software source packages using Major.minor.patch version ids. People download that, use it, sometimes update. They need know if they should update, and how much of a change it will be. The traditional format provides quick summary information on how much change they should expect, esp. if they should expect breaking changes.
* I manage a website where all data is stored server-side. We don't note version ids at all (you could use a github commit hash I guess, but no one cares). After all, users don't have any choice on "whether or not to update", so there's no need communicate that information.

I think the primary reason for a version identifier is to help users answer questions about change. E.g., "should I update?", "should I use this (or go back to using it)?", "is there a risk my data will break?", "Is there a risk the UI will no longer work the way I expect?"

This is a JavaScript client-side application, but you *can* extract data from it & store it elsewhere. If there's a risk of data suddenly being unreadable or misunderstood 1that could be a problem. But I guess most of the time that's not true, so maybe that's less of an issue.

So while I prefer major.minor.patch, I guess you've convinced me that single-digit is good enough. In almost all cases the data loss won't happen, and people will quietly update anyway.

That said, there's always a risk of an unexpected problem. I have two suggestions:

* Keep older ones available on request. I think you're doing that anyway.
* Embed the "current version of Metamath-lamp" in the JSON when you export it. That way, if there's a problem reading it in the future, there's a hint about what version to use. Hopefully that'll never be needed, but I've had a career of fixing "can't happen" scenarios, it's better to take simple steps to prepare for them :-).

**Comment by expln** [comment]
> Keep older ones available on request. I think you're doing that anyway.

Yes, I am doing it now. When I will be running out of space in my repo, I will start removing old and/or buggy versions.

> Embed the "current version of Metamath-lamp" in the JSON when you export it. That way, if there's a problem reading it in the future, there's a hint about what version to use. It will also help you implement "automatic conversion" if necessary. Hopefully that'll never be needed, but I've had a career of fixing "can't happen" scenarios, it's better to take simple steps to prepare for them :-).

Ok, that's a good idea. I will do. https://github.com/expln/metamath-lamp/issues/128

> I guess I don't understand your comment about disabling caching then. Can you please help me understand?

Sure. Let's say an app needs three files: index.html, main.js and worker.js. Functions in all of these files interchange data between each other, so these files should come from the same git commit to work correctly (ruffly speaking).

Now let's say we release version 1 of the app, but its URL doesn't include any identifier of the version.
In that case a user goes to the app's URL https://my-site.org/index.html and that page downloads the two remaining files:

https://my-site.org/main.js
https://my-site.org/worker.js

Now let's say we release version 2 of the app. Again the same user navigates to https://my-site.org/index.html. But all the resources referenced from this page were cached by the browser, and the browser doesn't try to download newer versions of main.js and worker.js. It instead uses cached versions. As a result the user doesn't see the update.

This problem may be solved by disabling caching for https://my-site.org/index.html. And probably that would be enough, because if the page is not cached then it will always be downloading the latest versions of main.js and worker.js. But in my programming experience I faced a lot of cases when somehow (I still don't understand how) some resources are cached and others are not. This may lead to different versions of main.js and worker.js are used together and cause incompatibility issues.

So I decided to put the version number to all URLs to make them unique, and to force browsers to download them each time a new version is released.

I disabled caching of https://expln.github.io/lamp/latest/index.html. But anyway this page gets cached somehow. But I hope it is cached for much shorter period of time than if caching would not be disabled.

**Comment by david-a-wheeler** [comment]
This issue is about updating for v11. That's done, so I'm closing this issue.
